use_frameworks!
inhibit_all_warnings!

target 'SDWebImageFLPlugin_Example' do
  pod 'SDWebImageFLPlugin', :path => '../'
  pod 'SDWebImage/Core', :path => '../../SDWebImage'

  target 'SDWebImageFLPlugin_Tests' do
    inherit! :search_paths

    
  end
end
