use_frameworks!
inhibit_all_warnings!
platform :ios, '8.0'
install! 'cocoapods', :share_schemes_for_development_pods => ['SDWebImageFLPlugin']

target 'SDWebImageFLPlugin_Example' do
  pod 'SDWebImageFLPlugin', :path => '../'
  pod 'SDWebImage/Core', :git => 'https://github.com/rs/SDWebImage.git', :branch => '5.x'

  target 'SDWebImageFLPlugin_Tests' do
    inherit! :search_paths
    pod 'Expecta'
    
  end
end
